# Generated by Django 4.1 on 2022-08-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo', verbose_name='фотография'),
        ),
        migrations.AlterField(
            model_name='client',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='bottles_ordered',
            field=models.IntegerField(default=1),
        ),
    ]
